language: scala
sudo: false
scala:
- 2.10.5
- 2.11.7
jdk:
- oraclejdk7
- oraclejdk8
script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test scalastyle && sbt ++$TRAVIS_SCALA_VERSION
  coverageAggregate
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/0a8b576604fce1b34b3e
    on_success: change
    on_failure: always
    on_start: false
